language: android
sudo: required
jdk: oraclejdk8

env:
 global:
 - ANDROID_BUILD_TOOLS=25.0.3
 - ADB_INSTALL_TIMEOUT=5 # minutes
 
android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS

licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+

before_install:
- chmod +x gradlew
